### ISSUE TITLE
Fails trying to set canvas.toDataURL('image/jpeg');

### ISSUE THREAD

**Issue by lahdekorpi** [idevsoftware/js-background-blend-mode#1]
[Error] SecurityError: DOM Exception 18: An attempt was made to break through the security policy of the user agent.
    onload (blend-mode.js, line 40)

Line 40: canvas.toDataURL('image/jpeg');

**Comment by idevsoftware** [comment]
I don’t know much about DOM, security and restrictions nowadays but might it not be the case where your javascript is on a different domain than where the base document is document is being served from? Which browser/version are you using?

**Comment by lahdekorpi** [comment]
Turns out I was loading the image from a different hostname so it failed on that.
Thanks! :)
