### ISSUE TITLE
Not working on IE

### ISSUE THREAD

**Issue by ain** [idevsoftware/js-background-blend-mode#2]
I understand it's the same script published at http://codepen.io/brav0/pen/bJDxt which unfortunately does not work on IE :(

**Comment by idevsoftware** [comment]
This wasn't really created to work on IE - I don't even have how to test it. Also, this project should be deprecated by now, as most modern mobile and desktop browsers natively support CSS blend modes

**Comment by ain** [comment]
Correct, if you consider IE not to be modern http://caniuse.com/#feat=css-backgroundblendmode

**Comment by ain** [comment]
**UPDATE:** weirdly enough it actually works on IE, but not on Codepen. So all is good, thanks for great work!

**Comment by idevsoftware** [comment]
That's good to know.
